# Generated by Django 3.0.3 on 2021-12-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('IDddd', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('brand', models.TextField(default='', max_length=100)),
                ('model', models.TextField(default='', max_length=100)),
                ('size', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('price', models.FloatField(default='')),
                ('colour', models.TextField(default='', max_length=15)),
            ],
        ),
    ]
