# Generated by Django 3.2.5 on 2021-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.TextField(max_length=1)),
                ('telephone', models.CharField(max_length=9)),
                ('city', models.TextField(max_length=100)),
                ('street', models.TextField(max_length=100)),
                ('street_number', models.TextField(max_length=10)),
                ('flat_number', models.TextField(max_length=10)),
                ('postal_code', models.TextField(max_length=6)),
            ],
        ),
    ]
