# Generated by Django 3.0.3 on 2021-12-08 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('brand', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('colour', models.TextField(max_length=15)),
                ('Picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
