# Generated by Django 3.0.3 on 2021-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='IDddd',
            field=models.AutoField(db_index=True, default=1, primary_key=True, serialize=False),
        ),
    ]
