# Generated by Django 3.0.3 on 2021-12-12 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20211212_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_ID', models.AutoField(db_index=True, default=1, primary_key=True, serialize=False)),
                ('Client_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Products')),
            ],
        ),
    ]
