# Generated by Django 3.0.3 on 2021-12-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211208_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
