# Generated by Django 3.0.3 on 2021-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Picture',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
