# Generated by Django 3.0.3 on 2021-12-08 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_auto_20211208_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.TextField(max_length=1)),
                ('telephone', models.CharField(max_length=9)),
                ('city', models.TextField(max_length=100)),
                ('street', models.TextField(max_length=100)),
                ('street_number', models.TextField(max_length=10)),
                ('flat_number', models.TextField(max_length=10)),
                ('postal_code', models.TextField(max_length=6)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('brand', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('colour', models.TextField(max_length=15)),
                ('Picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
