# Generated by Django 3.0.3 on 2021-12-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_clients_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
