# Generated by Django 3.0.3 on 2021-12-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='IDddd',
            new_name='Product_ID',
        ),
    ]
