# Generated by Django 3.2.5 on 2021-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.TextField(choices=[('A', 'Adidas'), ('N', 'Nike')], default='', max_length=100),
        ),
    ]
