# Generated by Django 3.0.3 on 2021-12-08 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.TextField(max_length=1)),
                ('telephone', models.CharField(max_length=9)),
                ('city', models.TextField(max_length=100)),
                ('street', models.TextField(max_length=100)),
                ('street_number', models.TextField(max_length=10)),
                ('flat_number', models.TextField(max_length=10)),
                ('postal_code', models.TextField(max_length=6)),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
