# Generated by Django 3.0.3 on 2021-12-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
    ]
