# Generated by Django 3.0.3 on 2021-12-08 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211208_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default='TBU', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='TBU', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_number',
            field=models.TextField(default='TBU', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='TBU', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.TextField(default='TBU', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.TextField(default='TBU', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(default='TBU', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_number',
            field=models.TextField(default='TBU', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(default='TBU', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='TBU', max_length=9),
        ),
    ]
