# Generated by Django 3.0.3 on 2021-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211208_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat_number',
            field=models.TextField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.TextField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_number',
            field=models.TextField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default=' ', max_length=9),
        ),
    ]
